[package]
edition = "2024"
name = "javy-plugin"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]
name = "javy_plugin"

[dependencies]
anyhow = "1.0"
# javy-plugin-api = {version = "5.0.0-alpha.1", git = "https://github.com/bytecodealliance/javy", features = ["json"]}
javy-plugin-api = {version = "5", features = ["json"]}
serde = {version = "1.0", features = ["derive"]}
serde_json = {version = "1.0"}
wit-bindgen = {version = "0.49"}

[profile.release]
codegen-units = 1 # Allows LLVM to perform better optimization.
debug = false # Disables debug information.
incremental = false # Disables incremental compilation.
lto = true # Enables link-time-optimizations.
opt-level = "s" # Prioritizes small binary size. Use `3` if you prefer speed.
panic = "abort" # Higher performance by disabling panic handlers.         
# strip = true # Ensures debug symbols are removed.
